const teachers=["Roy Tan","Santhi","Yih Check","Lim Xin Ying","Memymiswati","Michelle Han","Theint Theint","Yee Lin","Felix","Fan Rui Zhong","Li Zhi Ping","Ng Mei Ting","Chew Siew Keng","Sheryl Low","Loy Liang Teck","Edwin Chew","Fern","Kah Hsing"].map((name,i)=>({id:i+1,name,available:true}));
const sessions=[
{id:"AM",title:"First paper",papers:"G2/G3 EL Paper 2 · 08:00–09:50 | G1 EL Paper 2 · 08:00–09:20",shifts:["07:45–08:15","08:15–08:45","08:45–09:15","09:15–09:55"],rows:[["3R1","G3 EL P2","Hall"],["3R2","G3 EL P2","Hall"],["3R3","G3 EL P2","Hall"],["3R4","G3/G2 EL P2","Hall"],["3R5","G3/G2 EL P2","Hall"],["3R6","G2 EL P2","Hall"],["3R7","G2 EL P2","Hall"],["3R7","G1 EL P2","Comp Lab 1"],["3R7","G1 EL P2","Comp Lab 2"]]},
{id:"PM",title:"Second paper",papers:"G2/G3 EL Paper 1 · 11:00–12:50 | G1 EL Paper 1 · 11:00–12:20",shifts:["10:45–11:15","11:15–11:45","11:45–12:15","12:15–12:55"],rows:[["3R1","G3 EL P1","Hall"],["3R2","G3 EL P1","Hall"],["3R3","G3 EL P1","Hall"],["3R4","G3/G2 EL P1","Hall"],["3R5","G3/G2 EL P1","Hall"],["3R6","G2 EL P1","Hall"],["3R7","G2 EL P1","Hall"],["3R7","G1 EL P1","Comp Lab 1"],["3R7","G1 EL P1","Comp Lab 2"]]}
];let assignments={},locks={};
const key=(s,r,c)=>s+"-"+r+"-"+c;
function eligible(){return teachers.filter(t=>t.available)}
function load(id){return Object.values(assignments).filter(x=>x==id).length}
function generate(onlyUnlocked=false){const pool=eligible();sessions.forEach(s=>s.rows.forEach((r,ri)=>s.shifts.forEach((_,ci)=>{let k=key(s.id,ri,ci);if(onlyUnlocked&&locks[k])return;let used=s.rows.map((_,x)=>assignments[key(s.id,x,ci)]).filter(Boolean);let choices=pool.filter(t=>!used.includes(t.id)).sort((a,b)=>load(a.id)-load(b.id)||a.name.localeCompare(b.name));assignments[k]=choices[0]?.id||null})));render();toast(onlyUnlocked?"Unlocked slots regenerated":"Deployment generated")}
function validate(){let issues=0;document.querySelectorAll(".conflict").forEach(x=>x.classList.remove("conflict"));sessions.forEach(s=>s.shifts.forEach((_,ci)=>{let seen={};s.rows.forEach((r,ri)=>{let k=key(s.id,ri,ci),id=assignments[k];if(!id){issues++;return}if(seen[id])issues++;seen[id]=1;let t=teachers.find(x=>x.id==id);if(t&&!t.available)issues++})}));document.getElementById("issueCount").textContent=issues;document.getElementById("health").innerHTML=issues?("⚠ <b>"+issues+" issue(s)</b> found. Review unfilled, unavailable or duplicate assignments."): "✓ <b>Deployment valid.</b> All slots filled, no same-shift double bookings, all assigned teachers available.";toast(issues?"Validation found issues":"Validation passed")}
function render(){let schedule=document.getElementById("schedule");schedule.innerHTML="";sessions.forEach(s=>{let sec=document.createElement("div");sec.className="session";sec.innerHTML='<div class="sessionhead"><div><h3>'+s.title+'</h3><span class="muted">'+s.papers+'</span></div></div><div class="tablewrap"><table><thead><tr><th>Class</th><th>Subject</th><th>Venue</th>'+s.shifts.map((x,i)=>'<th>Shift '+(i+1)+'<br><span class="muted">'+x+'</span></th>').join("")+'</tr></thead><tbody>'+s.rows.map((r,ri)=>'<tr><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td>'+s.shifts.map((_,ci)=>slotHTML(s,ri,ci)).join("")+'</tr>').join("")+'</tbody></table></div>';schedule.appendChild(sec)});
document.querySelectorAll("select[data-key]").forEach(el=>el.addEventListener("change",e=>{assignments[e.target.dataset.key]=Number(e.target.value)||null;render();validate()}));document.querySelectorAll(".lock").forEach(b=>b.addEventListener("click",()=>{locks[b.dataset.key]=!locks[b.dataset.key];render()}));renderStaff();updateStats()}
function slotHTML(s,ri,ci){let k=key(s.id,ri,ci),v=assignments[k]||"";return '<td><div class="slot"><select data-key="'+k+'" '+(locks[k]?"disabled":"")+'><option value="">Unfilled</option>'+teachers.filter(t=>t.available||t.id==v).map(t=>'<option value="'+t.id+'" '+(t.id==v?"selected":"")+'>'+t.name+'</option>').join("")+'</select><button class="lock '+(locks[k]?"locked":"")+'" data-key="'+k+'" title="Lock assignment">'+(locks[k]?"🔒":"🔓")+'</button></div></td>'}
function renderStaff(){let el=document.getElementById("staffList");el.innerHTML=teachers.map(t=>'<div class="staffcard"><div><b>'+t.name+'</b><small>'+load(t.id)+' assigned shifts</small></div><label><input type="checkbox" data-staff="'+t.id+'" '+(t.available?"checked":"")+'> Available</label></div>').join("");el.querySelectorAll("[data-staff]").forEach(c=>c.addEventListener("change",e=>{teachers.find(t=>t.id==e.target.dataset.staff).available=e.target.checked;render();validate()}))}
function updateStats(){document.getElementById("staffCount").textContent=teachers.length;let slots=sessions.reduce((n,s)=>n+s.rows.length*s.shifts.length,0);document.getElementById("slotCount").textContent=slots;document.getElementById("filledCount").textContent=Object.values(assignments).filter(Boolean).length}
function renderSetup(){document.getElementById("sessionCards").innerHTML=sessions.map(s=>'<div class="sessioncard"><h3>'+s.title+'</h3><p>'+s.papers+'</p>'+s.shifts.map((x,i)=>'<span class="pill">Shift '+(i+1)+' · '+x+'</span>').join("")+'<p class="muted">'+s.rows.length+' deployment positions per shift</p></div>').join("")}
function toast(x){let t=document.getElementById("toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
document.getElementById("generate").onclick=()=>generate(false);document.getElementById("regen").onclick=()=>generate(true);document.getElementById("validate").onclick=validate;document.getElementById("addTeacher").onclick=()=>{let n=prompt("Teacher name");if(n&&n.trim()){teachers.push({id:Date.now(),name:n.trim(),available:true});render()}};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tabpanel").forEach(x=>x.classList.add("hidden"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.remove("hidden")});renderSetup();render();validate();